### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#1]
We need support for CORS, currently @moshfeu had to create a proxy in order to access the API deployed at api.codingcoach.io

We are going to deploy a development API frontend devs can use in their local environments, so they don't have to install the backend in their local.

I think we should use an environment variable to set the `origin` value, in development we will have `origin=*` but when going to production `origin=codingcoach.io`

Here's are some links on how enable CORS in nestjs
https://docs.nestjs.com/techniques/security#cors
https://github.com/expressjs/cors#configuration-options

**Comment by brentmclark** [comment]
I can grab this one.
