### ISSUE TITLE
Add a mentor to an existing list

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#100]
We want to allow users to add mentors to any of the available lists. We need an endpoint to update add a new mentor to the existing list.

Request
```
PUT /users/{user._id}/lists/{list._id}/add

{
  mentors: [{ _id: "12345"}, { _id: "a user._id"}]
}
```

Response
```
{ success: true }
```

**Restrictions**
- Members can only add their mentors to their own lists
- Admins can add mentors to any list

**Comment by MuthomiMate** [comment]
@crysfel I can work on this

**Comment by crysfel** [comment]
@MuthomiMate  All yours!!
