### ISSUE TITLE
Set max length to 400

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#101]
https://github.com/Coding-Coach/find-a-mentor-api/blob/3b989c5944974c7c750f6f07aefb6fe5286156be/src/modules/common/dto/application.dto.ts#L22

**Comment by brentmclark** [comment]
I can grab this if no one else wants it, although it's a great way to +1 your Hacktoberfest count!

**Comment by moshfeu** [comment]
> I can grab this if no one else wants it, although it's a great way to +1 your Hacktoberfest count!

I've enough t-shirts 😂

**Comment by crysfel** [comment]
@brentmclark all yours!!
