### ISSUE TITLE
Delete a mentor list

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#117]
We want to allow users to remove the existing lists, we need to create a new endpoint to remove a list from the database.

Request:
```
DELETE /users/{user._id}/lists/{list._id}
```

Response:
```
{ success: true }
```

**Restrictions**
- Users can remove their own lists only
- Admins can remove other user's lists

**Comment by davidkwan95** [comment]
Hi @crysfel , I would like to try and take on this issue

**Comment by crysfel** [comment]
@davidkwan95 all yours!! Let me know if you have any question
