### ISSUE TITLE
Allow mentor to set their availability to false

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#118]
We want to allow mentors to set their availability, for that we are going to add a new `available` property to the user model.

1. Allow to mentor to set that prop as `true` or `false`. We are going to reuse our existing API to edit the user model.
For new mentor, that prop will be `true` by default.
2. Write (and run) a script that migrate all existing mentors and add this prop as `true`.

Request
```
PUT /users/{user._id}

{
  available: true | false
}
```

Response
```
{ success: true }
```

**Restrictions**
- Only current user can update this value
- Admin can update this value for any other user
- Only users with `Mentor` role can update this value

**Comment by crysfel** [comment]
@moshfeu I've updated this issue, we are going to use the same endpoint we have when updating users, I also added some restrictions

**Comment by moshfeu** [comment]
Ok
