### ISSUE TITLE
Add endpoint - upload avatar

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#128]
PUT - `/users/{id}/avatar`

It should

1. Upload the file to (? @crysfel where the avatars will be hosted)
2. Set the user's avatar to that URL

**Comment by crysfel** [comment]
I'm thinking on setting up an S3 account to save the avatars and images/assets we need.

**Comment by crysfel** [comment]
For now I'm going to use the same server that is hosting the node app, just to keep the expenses down :)

**Comment by moshfeu** [comment]
Sounds good to me
