### ISSUE TITLE
Update UserDTO

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#129]
Add 

- [ ] timezone
- [ ] available - should be `enum` instead of `boolean`? 
- [ ] capacity

I know that we talked about it a lot but maybe we can split the models somehow because mentees have nothing with `capacity` or available. Even of not in the database, at least in the code..

**Comment by Rohithgilla12** [comment]
Hey I want to try this issue!
Can i take it up?

**Comment by moshfeu** [comment]
@crysfel ?

**Comment by crysfel** [comment]
@Rohithgilla12 all yours! Thanks!

**Comment by Rohithgilla12** [comment]
Thanks I followed [this](https://github.com/Coding-Coach/find-a-mentor-api/blob/master/CONTRIBUTING.md) to setup, what else I need to start working on this.

Thanks, waiting for response

**Comment by crysfel** [comment]
You should be up and running by following the guide

**Comment by Rohithgilla12** [comment]
Yeah I set it up, how do I check the things.
Do I also need to run `find-a-mentor` repository also?

**Comment by moshfeu** [comment]
No. The client is not using it yet.
You can verify it using postman or any other rest clients.

**Comment by Rohithgilla12** [comment]
How do I solve ` "No authorization token was found"` error

**Comment by Rohithgilla12** [comment]
It would be great if you can say, how to create a account, get a authorization token and use it.
Thanks.
Sorry to disturb.

**Comment by crysfel** [comment]
> Do I also need to run `find-a-mentor` repository also?

yes, I usually run `find-a-mentor` to get the token and use the local backend, you will have to update the API url here: https://github.com/Coding-Coach/find-a-mentor/blob/master/.env#L1 to point to your localhost server

**Comment by moshfeu** [comment]
@crysfel, @Rohithgilla12 can take the token from the mentors staging site: https://mentors-staging.codingcoach.io/

**Comment by Rohithgilla12** [comment]
<img width="1440" alt="Screenshot 2020-01-28 at 10 28 03 PM" src="https://user-images.githubusercontent.com/19389850/73286465-95077480-421d-11ea-85ee-0828f7166cd0.png">

**Comment by Rohithgilla12** [comment]
Also, after getting access token, how to use that in Postman.
SS would be perfect help.
Once I get started, I will add all these in the contributing document.

**Comment by moshfeu** [comment]
Apparently, I dropped from the server but it was cache in my browser.
I re-deployed it now, please check.

You should add token in the authorization tab

<img width="1119" alt="Screen Shot 2020-01-28 at 19 56 48" src="https://user-images.githubusercontent.com/3723951/73291166-56b38a80-4208-11ea-9c08-b25ba2c8a972.png">
