### ISSUE TITLE
Resize avatars on upload

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#132]
We need to resize images to the size we need for avatars. For that we are going to use https://github.com/lovell/sharp

AC
- Install `sharp` for resizing images
- Create a thumbnail image from the original
- Set the `avatar` field in user record to the thumbnail image
- Make sure to remove avatars when removing a user
- Make sure to remove thumbnail when updating a new image

**Comment by moshfeu** [comment]
@crysfel , what's the status of this one? It blocks up from deploy this: https://github.com/Coding-Coach/find-a-mentor/pull/675 (I merged it but reverted. I will be happy to deploy it again)
