### ISSUE TITLE
Unable to signup as a mentor because of the avatar validation error

### ISSUE THREAD

**Issue by Nkemjiks** [Coding-Coach/find-a-mentor-api#133]
<img width="791" alt="Screenshot 2020-02-11 at 4 58 44 PM" src="https://user-images.githubusercontent.com/32465536/74421809-e767a880-4e4d-11ea-8bf4-bc9a01b024e2.png">

I got this error when i tried working on adding myself as a mentor. Its currently blocking me from on this [issue](https://github.com/Coding-Coach/find-a-mentor/issues/673).

**Comment by crysfel** [comment]
Thanks for reporting this problem, I think we don't need to send the avatar field anymore, as this value will get dynamically set by the server when uploading the avatar.

I'm going to update the endpoint to ignore this field and remove the validation. In the meantime, you might want to remove the field from the payload

**Comment by crysfel** [comment]
Fixed by @moshfeu #134
