### ISSUE TITLE
New endpoint to get all mentorship requests

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#141]
## Description
We need a new endpoint to get all existing mentorship applications for a given user, this endpoint will return applications from me and to me, in other words there might be the case where a mentor is also a mentee.

Request:
```
GET /mentorships/${mentor.id}/requests
```

Response:
```
{
  success: true,
  data: [
    {
      id: number,
      mentor: { id: number, name: string, avatar: string, title: string }, 
      mentee: { id: number, name: string, avatar: string, title: string }, 
      status: string, 
      date: Date,
      message: string,
      background: string,
      expectation: string,
      isMine: boolean
    }
  ] 
}
```

AC
- Returns all applications for the given user
- Members can only see their own applications requests
- Mentors can see applications for them
- Only admins can fetch applications for other users

**Comment by crysfel** [comment]
I've updated the response to add a few missing fields:

```
      message: string,
      background: string,
      expectations: string,
```

**Comment by Mooli88** [comment]
@crysfel The endpoint got a spelling mistake. 
`GET /mentorhips/${mentor.id}/requests`
**mentorhips** to  **mentorships**

**Comment by Mooli88** [comment]
@crysfel @mia01 I think we need to add status "Pending"
https://github.com/Coding-Coach/find-a-mentor-api/blob/master/src/modules/mentorships/interfaces/mentorship.interface.ts#L3

**Comment by crysfel** [comment]
There's no need, we are going to show Pending when the status is `New`, then it will go to `View` when the user mentor views the request, then to `accepted` or `declined`.

Or, we can even just show `New` in the UI, and don't use `Pending` at all 🤔

**Comment by Mooli88** [comment]
> There's no need, we are going to show Pending when the status is `New`, then it will go to `View` when the mentor views the request, then to `accepted` or `declined`.
> 
> Or, we can even just show `New` in the UI, and don't use `Pending` at all 🤔

I thought you might say that. What's the reason for those extra steps (mapping New to Pending, Rejected to Decliend)? 
In my opinion, New and Pending should be separated statuses both for saving the UI extra (and somewhat confusing) step of mapping the values and also to actually distinguished between New and Pending.
So like unread email, once Mantor clicked on the request to read the message it will go from New to Pending.t do you think
But if anything we should show Pending over New. Its just make more sense to me this way 🤷‍♂️ 

What do you think?

**Comment by crysfel** [comment]
Yeah, `Pending` is confusing, we don't even have a pending status in the database, the idea is something like this:

*Happy path*
1. `New` the mentor hasn't seen the request
1. `Viewed` The mentor has seen the request, but haven't accepted nor rejected it.
1. `Accepted` The mentor accepted the request

*Declined*
1. `New`
1. `Viewed`
1. `Rejected` The mentor declined the request, the UI should show Declined.

*Canceled by the mentee*
1. `New`
1. `Canceled` The mentee canceled the request, for whatever reason (we are not supporting this status for the first iteration, although it doesn't matter for the backend)

We can use different labels in the UI, but these are the three scenarios we are considering a request will go.

**Comment by crysfel** [comment]
To avoid the mapping on the UI, we can definitely change the labels in the server, we are not live yet so now is a good time to decide the names. Let's discuss this tomorrow in our bi-weekly call.

**Comment by Mooli88** [comment]
> To avoid the mapping on the UI, we can definitely change the labels in the server, we are not live yet so now is a good time to decide the names. Let's discuss this tomorrow in our bi-weekly call.

Personally, I don't have a strong opinion about the labels naming. 
I think you or/and @moshfeu should just make the call about it.

New, Accepted and Declined make sense to me.

**Comment by Mooli88** [comment]
@crysfel Should I use the same endpoint to get all mentorship request for a mentee?
`GET /mentorships/${mentee.id}/requests` ?

**Comment by crysfel** [comment]
Yes, same endpoint! The user object will be the mentor's info for that case.

**Comment by crysfel** [comment]
@Mooli88 I've updated the response, instead of returning a single user we are going to return the mentor and the mentee and let the client decide which user render on the widget based on `isMine`

**Comment by Mooli88** [comment]
> @Mooli88 I've updated the response, instead of returning a single user we are going to return the mentor and the mentee and let the client decide which user render on the widget based on `isMine`

wouldn't it be simpler for the server to check the `isMine` and send the correct user?

**Comment by moshfeu** [comment]
Actually we can save a request and feed both the cards (my mentors and my mentees) with the request. In the future I mean.

**Comment by crysfel** [comment]
@Mooli88 there's an edge case when an admin calls this endpoint, which user should we return? The mentor, the mentee? We don't have a UI for this scenario at this point, but I think this endpoint should be ready to handle this case.

**Comment by mia01** [comment]
> Yeah, `Pending` is confusing, we don't even have a pending status in the database, the idea is something like this:
> 
> _Happy path_
> 
> 1. `New` the mentor hasn't seen the request
> 2. `Viewed` The mentor has seen the request, but haven't accepted nor rejected it.
> 3. `Accepted` The mentor accepted the request
> 
> _Declined_
> 
> 1. `New`
> 2. `Viewed`
> 3. `Rejected` The mentor declined the request, the UI should show Declined.
> 
> _Canceled by the mentee_
> 
> 1. `New`
> 2. `Canceled` The mentee canceled the request, for whatever reason (we are not supporting this status for the first iteration, although it doesn't matter for the backend)
> 
> We can use different labels in the UI, but these are the three scenarios we are considering a request will go.

ok so we are decided on the following @crysfel ?
```
new
viewed
accepted
rejected
canceled
```

I can update this in the current PR #165

**Comment by crysfel** [comment]
Done!
