### ISSUE TITLE
Grammar fixes in the Mentor Application Approved template

### ISSUE THREAD

**Issue by mujz** [Coding-Coach/find-a-mentor-api#144]
I got the mentor application approval email (template ID: `d-bf78306901e747a7b3f92761b9884f2e`). It's very well written and exciting! Kudos to whoever put it together!

As I tend to be super nit picky, I noticed a few areas that could use improvement in grammar. Here they are:

> ... making a real difference in someones career.

Should be

> ... making a real difference in someone's career.

Notice the apostrophe between "someone" and "s"

> ... everyone working together for each others mutual benefit.

Should be

> ... everyone working together for each other's mutual benefit.

Notice the apostrophe between "other" and "s"

> ... to really embody the shining crusader of mentor ship that you're destined to become.

"mentor ship" should be one word, as "mentorship" with no space between mentor and ship.

Feel free to ignore these remarks as most people probably wouldn't notice them. I thought I'd share my findings anyway in case you'd like to make the suggested changes.

Not sure who to direct this feedback to, so I'll throw it in here for now. I hope this is the right channel, if not I apologize.

:v:

**Comment by crysfel** [comment]
Hi @mujz! Thank you so much for pointing this out. I've updated the template on Sendgrid!

Would be awesome if you can also take a look at the copy on our figma design files for the new features we are working not! Please ping me in slack and I can share the file with you.

Regards
