### ISSUE TITLE
Hide channels for all mentors in search page

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#176]
We want to hide the channels for all mentors, this information will now be private and is going to be shown only to the mentees that the mentor accepts on requests.

The idea is to show the channels only to people the mentor has accepted as mentees.

Endpoint to update:
```
/mentors
```

Expected response for all users that are not my mentors
```
{
  data: [
    { ..., channels: [] } // <--- Channels should be empty
  ]
}
```

Expected response for MY mentors
```
{
  data: [
    { ..., channels: [{}, {}, {}] } // <--- Channels for my mentors
  ]
}
```

**Comment by brentmclark** [comment]
@crysfel is anyone working on this yet?  If not I'm happy to dive in.

**Comment by crysfel** [comment]
All yours @brentmclark! We now have e2e tests working correctly! Please make sure to include an e2e test for the code you write. You can write a unit test if you want, but I think we don't really need them anymore.

**Comment by moshfeu** [comment]
@brentmclark, any updates here?
Thanks!

**Comment by brentmclark** [comment]
> @brentmclark, any updates here?
> Thanks!

Hey @moshfeu!

This is getting close to done.  I have the channels hidden by default now, and am about half done with making the channels visible for the mentors of the current user.

Currently stuck getting services injected into other services so I can leverage existing queries.  If that stays blocked for too long I'll concede and find another approach.
