### ISSUE TITLE
Bump docker node version from 8-alpine due to compatibility issues

### ISSUE THREAD

**Issue by Damilare1** [Coding-Coach/find-a-mentor-api#178]
```
find-a-mentor-api      | error sharp@0.25.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
find-a-mentor-api      | error Found incompatible module.
```

The sharp module is incompatible with the current node version in the Dockerfile.

**Comment by crysfel** [comment]
Hi @Damilare1! would you like to create a PR for this?

**Comment by Damilare1** [comment]
Hi @crysfel I already did in #179. For some reason, I can't link the PR to this issue.

**Comment by crysfel** [comment]
#179 has been merged, thanks!
