### ISSUE TITLE
Add everything to Docker

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#2]
It'd be great if we use docker to run the project :)

**Comment by elft3r** [comment]
Hey @crysfel, I can help you with this. 

Do you have already any ideas where I should start? If not, then I could start by providing a docker-compose for the local development.

**Comment by crysfel** [comment]
@elft3r sure! All we need is mongo + node. Ideally we should be able to just do `$ docker-compose up -d` and the environment should be ready for dev.
