### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#20]
When a new member signs up as a mentor, we need to send an email right after the user submitted the application. Informing them we will review their application shortly.

Once the admin accepts a mentor request, we need to send an email to the new mentor with a confirmation/welcome message.

If the admin rejects the application, we need to send another email notifying the user the application has been rejected, we need to include the reason why the admin rejected the application.

**Comment by davisokoth** [comment]
Could I pick this?

**Comment by crysfel** [comment]
@davisokoth sure! go ahead! I was thinking on creating an account at mailgun to send emails, also we need to add the user to a list in mailchip.

**Comment by davisokoth** [comment]
Hey @crysfel am rather held up right now. Feel free to reassign this in case someone else is interested

**Comment by moshfeu** [comment]
Seems like auth0 has this feature.

**Comment by moshfeu** [comment]
No they not..

**Comment by moshfeu** [comment]
I think we should send 2 emails. First, when a mentor sent application to inform that the application received and we review it asap. Second, when we approve him (the email we're sending now).

**Comment by crysfel** [comment]
Agreed, we need to send two emails. Also, need to define which email service we are going to use.

**Comment by brentmclark** [comment]
@crysfel thoughts on Mailgun?  I did some research last night and it seems like a good fit from a billing and usage perspective; it gives 10,000 monthly emails for free.  That said, I've never worked with it before, so I have no idea if it's the correct technical choice.

**Comment by crysfel** [comment]
I've used Mailgun before and is very easy to use it.

- They have a REST API that we can use to send emails,
- We can create lists for newsletters and send an email to all members in that list by just calling a REST API
- We can use templates for sending emails and replace name and other useful info
- Nice dashboard with analytics 
- They also send that information to your servers so you can create your own dashboard if you want.

**Comment by brentmclark** [comment]
Let's lock in on Mailgun, then.  I'll get started tonight.

**Comment by brentmclark** [comment]
Mailgun was a hot mess.  Neither the official node.js library nor the unofficial one they reference in their docs are actively supported; and they don't support es6 modules.  I switched to SendGrid and was up-and-running super fast.  Thoughts on switching to SendGrid?

They only support 100 emails per day, down from 10,000 per month, but I seriously doubt we need that many.  However, SendGrid splits their emails into two categories; transactional and marketing.  Transactional are capped at 100/day while marketing emails have a different cap at 6000/month.  Between the two, it's roughly 9,000/mo which is very comparable.

**Comment by moshfeu** [comment]
> They have a REST API that we can use to send emails,

🤔

If we'll use SendGrid for only the mentors welcome email and use auth0 for welcoming the regular users (auth0 does have welcoming email, we can't use it for mentors because it's not in the lifecycle of auth0) then 100 will be enough.

**Comment by moshfeu** [comment]
> They have a REST API that we can use to send emails,

🤔
I'm not sure 100 per day will be enough because we will send a verification emails to mentees too.

**Comment by brentmclark** [comment]
@moshfeu are you referring to an email sent out when new they create an account?

**Comment by moshfeu** [comment]
Not only mentors, but regular users.

**Comment by crysfel** [comment]
@brentmclark I'm ok switching to `SendGrid`. It's shame Mailgun doesn't support node anymore, the cap I believe is on the free account.

**Comment by brentmclark** [comment]
@moshfeu 
> Not only mentors, but regular users.

Right.  So would it work if we let `Auth0` send the **"Your account has been created"** emails and use SendGrid for our transactional emails, such as **"Your request to be a mentor has been approved"**?

If we do that I think we can stay safely below the 100/day cap.

Thoughts?

**Comment by moshfeu** [comment]
As much as I saw, auth0 is not provides emails at all, only for tests. We need to supply to auth0 an email provider so even the "Your account has been created" will be sent via that provider. We can set this provider to be SendGrid.
I also noticed that digital ocean has no smtp server too.

**Comment by brentmclark** [comment]
My apologies; I misunderstood.

Based on our slack conversation I'm going to roll forward with SendGrid and I will ensure I wire in both a "you're account has been created" email as well as a "You're a mentor now" email.

Thanks all!
