### ISSUE TITLE
Limit to 5 pending mentorship requests

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#206]
Currently, there are mentees who send  many requests (up to ~20) and many approved (up to ~9).

We should limit requests up to 5 pending / open at a time to avoid mentors who approved the mentorship but the mentee never reached out back because the mentee already has some mentors.

The feature has 2 parts:

- When sending a request, returns how many more requests the mentee can send (2, 1 or 0)
- When sending a request, if it exceed the limit, returns error with the message: **TBD**

**Comment by FraDiBen** [comment]
Hi @moshfeu ,
I'd like to work on this enhancement as a way to practice Typescript and contribute to the project :)

I've started exploring the API and the issue, here some of findings:

#### What I did

As per my understanding the enhancement should be done for the endpoint 

[<:mentorId>/apply](https://github.com/Coding-Coach/find-a-mentor-api/blob/3d2878f5b66c3b6e14828891250a52407c84e3cd/src/modules/mentorships/mentorships.controller.ts#L51) 

In particular, to limit the requests a mentee can send we need to check, when a  mentee applies for a new mentorship to _any_ mentor, how many mentorships _the mentee_  has in _NEW_ status. 
Possibly by adding a check around [this line](https://github.com/Coding-Coach/find-a-mentor-api/blob/3d2878f5b66c3b6e14828891250a52407c84e3cd/src/modules/mentorships/mentorships.controller.ts#L87) of the controller endpoint. I was thinking to add a new method to the [service class](https://github.com/Coding-Coach/find-a-mentor-api/blob/3d2878f5b66c3b6e14828891250a52407c84e3cd/src/modules/mentorships/mentorships.service.ts#L8) to do so, along the lines of:

```js
  async getMenteeMentorshipsByStatus(menteeId: string, statuses: Status[]): Promise<Mentorship[]>  {
    if (!isObjectId(menteeId)) {
      throw new BadRequestException('menteeId is not an objectId');
    }
    return this.mentorshipModel.find(
        {
          mentee: menteeId,
          status: {$in: statuses},
        })
        .exec();
  }
```

Is there a method in the service class that I can reuse instead?

#### What were the results

I've started adding some new [tests for the controller components ](https://github.com/Coding-Coach/find-a-mentor-api/blob/3d2878f5b66c3b6e14828891250a52407c84e3cd/src/modules/mentorships/__tests__/mentorships.controller.spec.ts#L66) to get familiar with the codebase and using mocks. Till now, I've worked on the the assumption that `pending / open` mentorship request are related only to the NEW status for the mentees. Is this the case or shall I take in consideration the VIEWED status?

Shall I look in other parts of the code to implement this change too? 

#### My Next steps / questions

- What's the `error message` the API should return in case the requested new mentorship are greater than 5 ?
 I was thinking something alone the lines : 
 
```js
 return {
                success: false,
                data: 'mentees pending/open mentorships request are limited to 5',
            };
```             
- How the do we intend to modify the successful return of the [<:mentorId>/apply](https://github.com/Coding-Coach/find-a-mentor-api/blob/3d2878f5b66c3b6e14828891250a52407c84e3cd/src/modules/mentorships/mentorships.controller.ts#L118) endpoint ? At the moment we return only a `200` status code, would be okay to return something along the lines of:

```js
 return {
                success: true,
                data: {  remaining_mentorships : 4 },
            };
```             

Thank you!

**Comment by moshfeu** [comment]
Hi, sorry for the late respond.
Thank your for taking the time on exploring this task, much appreciated and good job 😀


> Is there a method in the service class that I can reuse instead?

The closest one is [`findMentorshipsByUser`](https://github.com/Coding-Coach/find-a-mentor-api//blob/8375917a16ab5670b65bcce5f80da063e2976fbb/src/modules/mentorships/mentorships.service.ts#L72) but it does more work than we need (populate mentor / mentees) so your approach looks fine to me.

> Is this the case or shall I take in consideration the VIEWED status?

Yes. 

- The error message sounds good
- The success payload looks good. Just make it _cameCase_ - `remainingMentorships`

**Comment by FraDiBen** [comment]
Hi @moshfeu,

thank you for the answers to the questions, happy to know I've grasped the gist of the change. I'll open in the next days a draft PR so that review can start. 

Just one little clarification over:

> Is this the case or shall I take in consideration the VIEWED status?
> Yes.

The `yes` means : that pending / open mentorship are the ones in the `NEW` _and_ `VIEWED` status?

**Comment by moshfeu** [comment]
Sorry. "Viewed" considered as "New" so if a mentee has 5 viewed request, (s)he can't send more requests.

**Comment by FraDiBen** [comment]
Un-assigning this request to me as I'm having some difficulties to run e2e tests and issue like (https://github.com/Coding-Coach/find-a-mentor-api/issues/211) overlap with some of the work

**Comment by moshfeu** [comment]
All yours
