### ISSUE TITLE
Migrate the current mentors to mongo

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#26]
We need to create a script to pull the data from `mentors.json` and save to the DB. 

Additionally, when a new user registers, we need to find out if this new user is an existing mentor and link the new account to the profile.

**Comment by elft3r** [comment]
@crysfel Did you already do any work on this? I have a script locally which is importing the json file. If you haven't done any work yet, I could clean my script up and create a pull request.

**Comment by crysfel** [comment]
No, I was planning on working on this tonight but if you already have something, let's use that!

Please add your script here: https://github.com/Coding-Coach/find-a-mentor-api/tree/master/scripts

Thanks!

**Comment by crysfel** [comment]
Thanks for contributing
