### ISSUE TITLE
Remove channels from unauthenticated payload

### ISSUE THREAD

**Issue by brentmclark** [Coding-Coach/find-a-mentor-api#29]
Per [this TODO](https://github.com/Coding-Coach/find-a-mentor-api/blob/master/src/modules/mentors/mentors.controller.ts#L27) It would appear we need to delete the channels from the mentors payload for unauthenticated users.

Can you confirm that this is accurate @crysfel?

**Comment by crysfel** [comment]
Yes, we want users to login in order to contact mentors

**Comment by brentmclark** [comment]
OK Great!  The `TODO` mentions `other private data`; do you have a list of what that is?  Are we talking PII like `country` and `name`?  Or is it just the channels for now?

**Comment by crysfel** [comment]
Just the channels for now
