### ISSUE TITLE
Add channels to the mentor model

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#3]
```
{
  type: 'email' | 'slack' | 'linkedin' | 'facebook' | 'twitter' | 'github' | 'website',
  id: string
][]
```
minimum: 1
maximum: 3

Each one of them should be validating (as much as we can) following this table:
https://github.com/Coding-Coach/find-a-mentor#channels

**Comment by brentmclark** [comment]
I can take this one.

**Comment by moshfeu** [comment]
thanks

**Comment by elft3r** [comment]
@brentmclark can I help you in any way with this?

**Comment by brentmclark** [comment]
@elft3r thank you for the offer, but I'm almost done already.  I almost put up the PR two weeks ago but got sidetracked with a family vacation.  It'll be done shortly.

**Comment by moshfeu** [comment]
@elft3r we'll have a lot of tasks here. Stay turned 👍

**Comment by elft3r** [comment]
@brentmclark cool to hear that. I can't imagine a better way to get sidetracked from a project :-)

@moshfeu thanks for the update. i'm happy to help in any way I can, just let me know what I can do

**Comment by moshfeu** [comment]
@brentmclark Can you update the status please?

**Comment by brentmclark** [comment]
@moshfeu I have those last two items to tackle from the description.  @crysfel helped me through a few of the issues I was encountering on Friday, which was rad!  I have a few hours tonight to focus on this; should have a PR up tonight if things go well.
