### ISSUE TITLE
Better error messages for User data

### ISSUE THREAD

**Issue by brentmclark** [Coding-Coach/find-a-mentor-api#31]
Right now, if a `User` is updated with anything that fails validation at the DB level, the API returns a 500 with a generic response.  It would be much better if a `400` was returned with a specific error message so it's easier to figure out what went wrong.

**Comment by D4veCode** [comment]
I would like to take this!

**Comment by brentmclark** [comment]
@D4veCode it's yours!

**Comment by crysfel** [comment]
Thanks @D4veCode! We are already doing validations in other fields, such as validating if is a string, defined and so on.

Please take a look at the response when returning a validation error:

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "target": {
                "spokenLanguages": [
                    "en",
                    "es"
                ],
                "tags": [
                    12,
                    {}
                ],
                "channels": [
                    {
                        "type": "twitter",
                        "id": "@crysfel"
                    }
                ]
            },
            "value": [
                12,
                {}
            ],
            "property": "tags",
            "children": [],
            "constraints": {
                "isString": "each value in tags must be a string"
            }
        }
    ]
}```

This format is the one our validation library is using, so let's keep things consistent.

Thanks!

**Comment by D4veCode** [comment]
Sure @crysfel! I would take a look at that tonight! Obviously always trying to keep the consistency of the API!

**Comment by brentmclark** [comment]
@crysfel is this the standard error payload when the validations on the `dto` fail?  If so, this might be as simple as triggering validation on the nested models.

**Comment by crysfel** [comment]
> @crysfel is this the standard error payload when the validations on the `dto` fail?

Yes, this is the JSON the validation library returns when there are errors, I think we need to make sure to run those validations before trying to save to the database.

**Comment by brentmclark** [comment]
Ah, I see.  I never created a `ChannelDto` to match the `Channel` interface I created.  As such, there's no spot to add validation decorators.

@D4veCode, the scope of this has shifted a bit; I'm very sorry.  If you're still up for it, I think this become a bit easier, albeit more specific to the `class-validator` library.

**Comment by D4veCode** [comment]
Hi guys, I have two questions, first of them is how do you manage branches? It's just for keeping the consistency of the repo. Second one is, what are the Auth0 client and secret that I need to place in my .env file?

**Comment by brentmclark** [comment]
Hey @D4veCode, I can share these credentials with you in a DM.

**Comment by crysfel** [comment]
@D4veCode all you need is to create an account in auth0, then create two apps in there:

1. A single page application app
2. A machine to machine app

The you can use the keys you get in there ;)

**Comment by brentmclark** [comment]
@D4veCode I am so sorry; I just realized I never answered your question about branches.  Is that still an open question?  Are you blocked by anything else I can help you with?

**Comment by crysfel** [comment]
Hi @D4veCode, I'm wondering if you have any progress on this issue?

**Comment by D4veCode** [comment]
Hi @crysfel, I've been very busy in my job! I hace started to work with the issue but I haven't finished yet, I hope to finish it by the end of the month! I'm sorry!

**Comment by Jolg42** [comment]
Hi there!

I was curious and tried to fix it, but unfortunately it's impossible to setup the project, there is no seed to populate the database. (There is one but outdated and broken). So if someone could update the contributing documentation that will be awesome for new contributors.

For the solution it looks like you'll need to create an `exceptionFactory` function based on what I see here 
https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L92
and in the [docs](https://docs.nestjs.com/pipes#the-built-in-validationpipe)

Like this 
```ts
new ValidationPipe({
  exceptionFactory: (errors: ValidationError[]) => 
    new BadRequestException('Validation error'),
});
```

And you may want to also add this to remove the extra objects:
```ts
new ValidationPipe({
  validationError: { 
	target: false, 
	value: false 
  },
  exceptionFactory: (errors: ValidationError[]) => 
    new BadRequestException('Validation error'),
});
```

Check the dependencies and update `class-validator` too.
