### ISSUE TITLE
Mark User fields required at the database

### ISSUE THREAD

**Issue by brentmclark** [Coding-Coach/find-a-mentor-api#32]
As of now it's possible to get a user object into the database with invalid data.  To guard against this, the following fields on the `UserSchema` should be marked as required:

- [ ] `auth0Id`
- [ ] `email`
- [ ] `name`
- [ ] `avatar`

Look [here](https://github.com/Coding-Coach/find-a-mentor-api/blob/master/src/modules/users/schemas/user.schema.ts#L12) for an example of how to set a field in the schema as `required`.

**Comment by shayanypn** [comment]
For this issue, its just need to mark these fields are `required` ? doesn't need any changes in validation or any other part?

**Comment by brentmclark** [comment]
@shayanypn that's correct with the exception of `avatar` which is currently decorated as `@IsOptional` in the `dto`.  Perhaps @crysfel or @moshfeu can chime in here and educate us both on how they want to proceed.  

Do we want to make `avatar` required now, or leave it as optional?

**Comment by mkamranhamid** [comment]
Can I take this?

**Comment by moshfeu** [comment]
IMO, Avatar should be required. Anyway, auth0 are generate a generic one in the registration.

**Comment by brentmclark** [comment]
@moshfeu sounds good to me.  

@shayanypn given that we want to make `avatar` required, there would be an extra task of removing the optional decorate from the `avatar` field in the `dto`.  Were you interested in grabbing this?  Otherwise it looks like @mkamranhamid is willing to grab it.

**Comment by crysfel** [comment]
yes, let's make the `avatar` required, we are going to need a way to upload avatars, but that's coming later on :)

**Comment by shayanypn** [comment]
Great. Well I am working on it right now 😊

**Comment by brentmclark** [comment]
> Great. Well I am working on it right now 😊
