### ISSUE TITLE
Return appropriate status code on the request itself

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#4]
Right now, the api return always status code 200 and in the response itself, it returns the actual status.

<img width="633" alt="58616674-ef36eb00-82c6-11e9-8411-5397e506f1ca" src="https://user-images.githubusercontent.com/3723951/58650962-bcb5de00-8318-11e9-87c4-eed3ccc6ab55.png">
<img width="492" alt="58616673-ee9e5480-82c6-11e9-8945-f9982691ed95" src="https://user-images.githubusercontent.com/3723951/58650966-bde70b00-8318-11e9-9b6e-a80e9b9e667a.png">

**Comment by crysfel** [comment]
That might be the local proxy returning 200, this is the response form the api itself, as you can see in the following image there's a 400 status response.

<img width="965" alt="Screen Shot 2019-05-30 at 12 28 19 PM" src="https://user-images.githubusercontent.com/219207/58651338-aa1ab500-82d6-11e9-8cec-71abc2c48dbe.png">

There's this issue #1 that will add support for CORS, so we don't have to rely on a proxy

**Comment by moshfeu** [comment]
You're right!
