### ISSUE TITLE
Add instructions to the README on how to setup auth0

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#42]
We need to explain how to setup auth0 :)

**Comment by elft3r** [comment]
Hey,
I finally managed to setup auth0 for me locally, using the _Auth0 Management API_. Most likely that is not the best way to do it, however, as this is for development purposes only, I think this is okay for now.

If you are fine with this approach, I can add the instructions to the README.

**Comment by crysfel** [comment]
Yes, please do it! 🙏 Thank you so much!

**Comment by brentmclark** [comment]
Hey @elft3r, any update on this?

**Comment by crysfel** [comment]
I will take this one :)
