### ISSUE TITLE
Return consistency payload for all the requests

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#5]
The response will be:

```
{
  success: boolean,
  data: object (user / mentor / mentors)
}
```

https://github.com/Coding-Coach/find-a-mentor-api/blob/d5a091f9d390701f26ab51f0e5e9bccc1807d126/src/modules/users/users.controller.ts#L51-L54

Actually, I'm not sure about the `success: true`, since we will get the status implicit from the request's status code.

**Comment by brentmclark** [comment]
> Actually, I'm not sure about the status code, if we will get it anyway from the request's status code

Are you talking about `success:true` versus HTTP status 200?

**Comment by moshfeu** [comment]
> > Actually, I'm not sure about the status code, if we will get it anyway from the request's status code
> 
> Are you talking about `success:true` versus HTTP status 200?

Ya, sorry for the lame phrase
