### ISSUE TITLE
Set up swagger environment

### ISSUE THREAD

**Issue by brentmclark** [Coding-Coach/find-a-mentor-api#55]
Currently it's not possible to view the swagger docs without running the BE which comes with its own config requirements and dependencies.  It would be ideal to see the swagger docs on an established environment.

**Comment by crysfel** [comment]
There are a couple things to do in here:

1. We need to generate the swagger documentation JSON file every time there's a change in the API docs.
2. We need to create a swagger app and read the JSON file from github
3. Deploy the documentation app somewhere accessible by anyone
