### ISSUE TITLE
As a mentor is possible to enter an email address that is too long

### ISSUE THREAD

**Issue by janwilmans** [Coding-Coach/find-a-mentor-api#63]
**Describe the bug**
As a mentor is possible to enter an email address is too long (254+ chars)
Also there is an arbitrary limits of 50-100 chars?

**Expected behavior**
RFC5321 specifies an email address can't exceed 254 chars.
However, there is 71-char limit:
jan@abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde0123456789abc.com

reports no client side validation message, only:

![image](https://user-images.githubusercontent.com/5933444/63123732-f4dccc80-bfa9-11e9-9e75-1f7c21a1c1d8.png)

Also: the channel-email field takes a longer email address, I did not test its limits, but it appears to work fine.

**Comment by crysfel** [comment]
Thanks for reporting the issue...

Now that I think about it, we might not want to allow users to update their email, else we will have to also update the auth0 email.

As a user I'd expect that once updating my email in the app, next time I'd use the new email to login and that's currently not the case, I'm not sure if we can update the email in auth0.

As a solution to this bug, I'd suggest to not allow users to update their email, we also need to disable the textfield in the client.

@moshfeu what are your thoughts?

**Comment by moshfeu** [comment]
I agree. For now (unless there will be requests for this) we can remove that field from the form.
