### ISSUE TITLE
Reject reason should be appear in the rejection email

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#66]
Currently, when user receiving the rejection email he can't know why his application rejected.
Seems like sendGrid has params / placeholders mechanizm  - https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/#send-a-transactional-email

**Comment by brentmclark** [comment]
It was a deliberate decision to exclude the rejection reason from the email in favor of a softer approach.  We should discuss this further before adding the reason to the email.

**Comment by moshfeu** [comment]
Understandable, but we if we want to let user to know what he should fix? After all, we're the one we phrase the reason so we can do it soft by ourselves.

**Comment by crysfel** [comment]
Totally agreed with @moshfeu, The reason could be something like:

```
Hi there, I tried to open your linkedin URL but I'm a getting a 404 error, everything else looks great. Please update that url and apply again, then we should be good to go. Thanks!
```

Right now if there's an error we can't ask the user to fix it :(

**Comment by brentmclark** [comment]
Ah, ok.  This stems from a misunderstanding on my part.  I somehow convinced myself that the `reason` was something from a dropdown, which felt cold and incomplete.

If the reason is free text and contains actionable next steps then I am fully on board with this.

Very sorry for slowing this down.

**Comment by moshfeu** [comment]
When rejecting an application there is a text field (`prompt` to be exact) so the rejector can explain in free text why.

**Comment by crysfel** [comment]
The backend is ready for this and currently saving that data, all you need to do is pull the data from the database: https://github.com/Coding-Coach/find-a-mentor-api/blob/master/src/modules/common/schemas/application.schema.ts#L9

Then add it to the email before sending it.
