### ISSUE TITLE
Review a mentor or giving "kudos". 

### ISSUE THREAD

**Issue by levivm** [Coding-Coach/find-a-mentor-api#78]
I was thinking of a way for allowing users to review a mentor or giving him some kind of kudo(congrats) for his help. 

My suggested flow is:
1. User asks mentor help clicking in an action button.
2. Mentor accepts it. 
3. After being accepted, the user at any time could thank the mentor by a review or something like that. 

It is just an idea. But, having this we could have a base for a ranking system.

Regards.

**Comment by moshfeu** [comment]
Thanks for the idea!
We discussed about a feedback and ranking system almost from the beginning :)
We're keep thinking about that, how exactly it should behave so it will serve both mentors and mentees the best.
Also, as you presented it (and how we thought about that), it requires a connections system between mentors and mentees which is big feature by itself.
What I'm trying to say that it's a very important and powerful feature but IMO, it's not in the top of the list right now.
@crysfel, what do you think?

**Comment by levivm** [comment]
Hi, 

Thanks for the reply. 

I know that building a ranking system could take a lot of resources and time, a quick solution could be something like: 

1. Mentees click on an action button that says "This mentor helped me" (Of course, using a shorter text)
2. Mentor accepts it.
3. Mentor has a counter showing: How many mentees he has helped out. 

Regards
Levi.

**Comment by moshfeu** [comment]
Thanks again :)
We'll discuss about that and share the community of course.
