### ISSUE TITLE
Add and configure Sentry

### ISSUE THREAD

**Issue by brentmclark** [Coding-Coach/find-a-mentor-api#82]
**Is your feature request related to a problem? Please describe.**
We currently lack visibility into errors that occur on our site and rely on the goodwill of others to report these errors.  There are tools on the market that will automatically capture errors while providing enhanced workflows for resolving the bugs.  My favorite among these tools is [Sentry.io](https://sentry.io/welcome/); I've been using them for years with great success.

Sentry offers open-source sponsorship and has accepted our request for sponsorship because they. are. awesome.

The only thing left to do is actually install and configure their tool.  

---

If anyone has suggestions to offer, or questions before Sentry is installed please comment below.

**Comment by crysfel** [comment]
I think Sentry is the way to go!
