### ISSUE TITLE
Send deleted user email when user is deleted by admin

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/find-a-mentor-api#85]
We want to let the user to know that we deleted them.

https://github.com/Coding-Coach/find-a-mentor-api/blob/1eb4658757d9e1ef82d1a8b3717e4992351bb22b/src/modules/users/users.controller.ts#L171

Something like

```javascript
if (res.ok && current.roles.includes(Role.ADMIN)) {
  const emailData = {
    to: user.email,
    templateId: Template.USER_DELETED,
    dynamic_template_data: {
      reason: params.reason,
    },
  };

  this.emailService.send(emailData);
}
```

~I'll create the template in SendGrid~
Template Id: `de2e0c5217b6422a88274a6affd327e7`

Relates to: https://github.com/Coding-Coach/find-a-mentor/issues/628

**Comment by MuthomiMate** [comment]
@moshfeu @crysfel I would like to pick this up

**Comment by moshfeu** [comment]
Go for it, @crysfel, please priorities.
Notice that I added the template_id in the description.

**Comment by MuthomiMate** [comment]
ok cool Thanks

**Comment by crysfel** [comment]
@MuthomiMate all yours! I will help you set the project up. In the meantime:

- Open an auth0 account
- Open a sendgrid account

I need to write a document to show you how to setup those too.
