### ISSUE TITLE
fix the template_id for the user deletion email

### ISSUE THREAD

**Issue by MuthomiMate** [Coding-Coach/find-a-mentor-api#91]
I added my own test template id in this [PR](https://github.com/Coding-Coach/find-a-mentor-api/pull/88) and forgot to change it back to the correct template id that was created here [#85](https://github.com/Coding-Coach/find-a-mentor-api/issues/85)

**Comment by MuthomiMate** [comment]
@crysfel please go ahead and assign this to me

**Comment by moshfeu** [comment]
@crysfel is this deployed already?

**Comment by crysfel** [comment]
@moshfeu yes, it's deployed but only to staging. Once we test it work fine, we should deploy to production

**Comment by moshfeu** [comment]
Ok. I'll check that soon
