### ISSUE TITLE
Create mentors lists

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/find-a-mentor-api#98]
Users can create lists of mentors, for example: QA Mentors, Rockstars Devs, etc.. 

We need one endpoint to receive the name of the new list, along with the mentors we want to add to the list:

Request:
```
POST /users/{user._id}/lists

{
  "name": "QA Mentors",
  "public": false,
  "mentors": [{ _id: "1234" }, ... ]
}
```

Response:
```
{
  success: true,
  list: { _id: "12345" }
}
```

**Validations**
- `name` should be required
- `public` is optional and defaults to `false`
- `mentors` is optional and defaults to an empty array

**Restrictions**
- Members can create their own lists
- Members can't create lists for other members
- Admin can create lists for any other member

**Comment by moshfeu** [comment]
Sounds good.
To save requests (and also it make sense anyway) we can return those lists in the `users/current` endpoint too.

**Comment by moshfeu** [comment]
For now it could return only the "general" list, the ui will know to handle this

**Comment by brentmclark** [comment]
I like the idea of hitting a separate endpoint to get the list of lists as opposed to adding more to the `users/current` endpoint.  It's not the end of the world, of course, but I'm concerned about overloading that initial request.

**Comment by moshfeu** [comment]
> I like the idea of hitting a separate endpoint to get the list of lists as opposed to adding more to the `users/current` endpoint. It's not the end of the world, of course, but I'm concerned about overloading that initial request.

That makes sense too :)

**Comment by crysfel** [comment]
> I like the idea of hitting a separate endpoint to get the list of lists as opposed to adding more to the `users/current` endpoint. It's not the end of the world, of course, but I'm concerned about overloading that initial request.

Exactly what I was thinking, but again we can add it later if we see some benefits
